# Generated by Django 5.2.1 on 2025-10-05 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=200, verbose_name='Kitob nomi')),
                ('book_id', models.CharField(max_length=50, verbose_name='Kitob ID')),
                ('given_at', models.DateTimeField(auto_now_add=True, verbose_name='Berilgan vaqt')),
                ('return_due_date', models.DateTimeField(verbose_name='Qaytarish muddati')),
                ('returned', models.BooleanField(default=False, verbose_name='Qaytarilgan')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='kim tomonidan')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member', verbose_name='Talaba')),
            ],
            options={
                'verbose_name': 'Ijara',
                'verbose_name_plural': 'Ijaralar',
                'ordering': ['-given_at'],
            },
        ),
    ]
