# Generated by Django 5.2.1 on 2025-06-07 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=200, verbose_name='Kitob nomi')),
                ('book_id', models.CharField(max_length=50, verbose_name='Kitob ID')),
                ('given_at', models.DateTimeField(auto_now_add=True, verbose_name='Berilgan vaqt')),
                ('return_due_date', models.DateTimeField(verbose_name='Qaytarish muddati')),
                ('returned', models.BooleanField(default=False, verbose_name='Qaytarilganmi')),
            ],
            options={
                'verbose_name': 'Ijara',
                'verbose_name_plural': 'Ijaralar',
                'ordering': ['-given_at'],
            },
        ),
    ]
