# Generated by Django 5.2.1 on 2025-09-29 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='kim tomonidan'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='returned',
            field=models.BooleanField(default=False, verbose_name='Qaytarilgan'),
        ),
    ]
