# Generated by Django 5.2.1 on 2025-06-07 13:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Ism Familiyasi')),
                ('student_id', models.CharField(max_length=12, unique=True, verbose_name='Talaba ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='Faqat 9 xonali raqam kiriting, masalan: 901234567', regex='^[0-9]{9}$')], verbose_name='Telefon raqami')),
            ],
            options={
                'verbose_name': 'Talaba',
                'verbose_name_plural': 'Talabalar',
                'ordering': ['-created_at'],
            },
        ),
    ]
