# Generated by Django 5.2.1 on 2025-09-29 10:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['full_name'], 'verbose_name': 'Talaba', 'verbose_name_plural': 'Talabalar'},
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.CharField(max_length=9, unique=True, validators=[django.core.validators.RegexValidator(message='Telefon raqami 9 xonali bo‘lishi kerak. Masalan: 91 1234567', regex='^(20|36|33|50|55|61|62|65|66|67|69|70|71|72|73|74|75|76|77|78|79|88|90|91|93|94|95|97|98|99|)\\d{7}$')], verbose_name='Telefon raqami'),
        ),
        migrations.AlterField(
            model_name='member',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
